apiVersion: v1
kind: Pod
metadata:
  name: orders
  labels:
    name: orders
    app: orders
spec: 
  containers: 
    - image: ramyacodes/orders
      name: orders
      ports: 
        - containerPort: 4747
